php artisan krlove:generate:model Activity
php artisan krlove:generate:model BreastMilk
php artisan krlove:generate:model Children
php artisan krlove:generate:model Contraception
php artisan krlove:generate:model Family
php artisan krlove:generate:model Immunizations
php artisan krlove:generate:model Parent
php artisan krlove:generate:model ParentNote
php artisan krlove:generate:model Pregnant
php artisan krlove:generate:model Religion
php artisan krlove:generate:model Role
php artisan krlove:generate:model User
